version: "2"
prepare:
  fetch:
    - "https://raw.githubusercontent.com/internetee/style-guide/master/ruby/.rubocop.yml"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  rubocop:
    enabled: true
    channel: rubocop-0-58
exclude_patterns:
  - "config/"
  - "db/"
  - "test/"
