FROM internetee/ruby:2.6
LABEL org.opencontainers.image.source=https://github.com/internetee/whois

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install whois locales -y > /dev/null

# Setting locale 
RUN locale-gen et_EE.UTF-8
ENV LANG et_EE.UTF-8   
ENV LC_ALL et_EE.UTF-8

RUN mkdir -p /opt/webapps/app/tmp/pids
WORKDIR /opt/webapps/app

COPY . ./

RUN gem install bundler && bundle install --jobs 20 --retry 5


EXPOSE 43
