default: &default
  host: <%= ENV.fetch("APP_DBHOST") { "db" } %>
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("APP_DBUSER") { "postgres" } %>
  password: <%= ENV.fetch("APP_DBPASS") {  } %>

development:
  <<: *default
  database: registry_whois_development

test:
  <<: *default
  database: registry_whois_test

staging:
  <<: *default
  database: registry_whois_staging

production:
  <<: *default
  database: registry_whois_production
