default: &default
  host: db
  adapter: postgresql
  encoding: unicode
  username: postgresql
  password: 
  pool: 5

development:
  <<: *default
  database: registry_whois_development

test:
  <<: *default
  database: registry_whois_test

staging:
  <<: *default
  database: registry_whois_staging

production:
  <<: *default
  database: registry_whois_production
