#!/bin/bash
### BEGIN INIT INFO
# Provides:          Whois server
# Required-Start:    $all
# Required-Stop:     $network $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the Whois server
# Description:       Enable Whois server
### END INIT INFO

set -u
set -e

#
# Change these to match your server:
#
# Make sure that all paths are correct.
#
if [[ -z $APP_HOME ]]; then
  APP_HOME="/home/whois/whois"
else
  APP_HOME=$APP_HOME
fi

if [[ -z $APP_ROOT ]]; then
  APP_ROOT="$APP_HOME/current"
else
  APP_ROOT=$APP_ROOT
fi

if [[ -z $WHOIS_USER ]]; then
  WHOIS_USER=whois # or use some other unprivileged system user
else
  WHOIS_USER=$WHOIS_USER
fi

if [[ -z $WHOIS_ENV ]]; then
  WHOIS_ENV=production
else
  WHOIS_ENV=$WHOIS_ENV
fi

if [[ -z $RUBY_PATH ]]; then
  RUBY_PATH=/home/$WHOIS_USER/.rbenv/shims/ruby
else
  RUBY_PATH=$RUBY_PATH
fi    

cd $APP_ROOT || exit 1

case ${1-help} in
status)
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1         
        ;;
start)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1         
        ;;
stop)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1         
        ;;
force-stop)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb stop -f 
        ;;
reload)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1 
        ;;
restart)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1 
        ;;
*)
        echo >&2 "Usage: $0 <status|start|stop|force-stop|reload|restart>"
        exit 1
        ;;
esac
