#!/bin/bash
### BEGIN INIT INFO
# Provides:          Whois server
# Required-Start:    $all
# Required-Stop:     $network $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the Whois server
# Description:       Enable Whois server
### END INIT INFO

set -u
set -e

#
# Change these to match your server:
#
# Make sure that all paths are correct.
#
APP_HOME="/home/whois/whois"
APP_ROOT="$APP_HOME/current"
WHOIS_USER=whois # or use some other unprivileged system user
WHOIS_ENV=production
RUBY_PATH=/home/$WHOIS_USER/.rbenv/shims/ruby         

cd $APP_ROOT || exit 1

case ${1-help} in
status)
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1         
        ;;
start)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1         
        ;;
stop)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1         
        ;;
force-stop)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb stop -f 
        ;;
reload)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1 
        ;;
restart)
        echo "$1 whois monitor and server"
        cd $APP_ROOT && WHOIS_USER=$WHOIS_USER WHOIS_ENV=$WHOIS_ENV $RUBY_PATH whois.rb $1 
        ;;
*)
        echo >&2 "Usage: $0 <status|start|stop|force-stop|reload|restart>"
        exit 1
        ;;
esac
