name: build, test and deploy test environment on pr

on:
  push:
    branches:
    - temp_rake_db_in_container
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: ubuntu-20.04
  
    steps:

        - uses: actions/checkout@v2

        - name: Set image tag
          run: |
            SHORT_SHA=$(git describe --always)
            echo "internetee/whois:RC_$SHORT_SHA" > TAG

        - name: Set ENV for codeclimate (push)
          if: github.event_name == 'push'
          run: |
            echo "$GITHUB_REF" > GIT_BRANCH
            echo "$GITHUB_SHA" > GIT_COMMIT_SHA

        - name: Set ENV for codeclimate (pull request)
          if: github.event_name == 'pull_request'
          run: |
            echo "$GITHUB_HEAD_REF" > GIT_BRANCH
            echo "$(git rev-parse origin/$GITHUB_HEAD_REF)" > GIT_COMMIT_SHA
          

        - name: Build image
          run: |
            docker build -t $(cat TAG) .
        
        - name: Test
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          run: |
            docker network create --driver bridge test-net
            docker run -d --name db --network=test-net internetee/whois_tester_postgres:1
            docker run -d -e WHOIS_ENV=test -e APP_DBHOST=db -e GIT_COMMIT_SHA="$(cat GIT_COMMIT_SHA)" -e GIT_BRANCH=$(cat GIT_BRANCH) -e CC_TEST_REPORTER_ID --name whois --network=test-net $(cat TAG) tail -f /dev/null
            docker exec -i whois rake test

        - name: Get and upload test results
          run: |
            docker exec -i whois ./cc-test-reporter format-coverage --output coverage/codeclimate.json
            docker exec -i whois ./cc-test-reporter sum-coverage coverage/codeclimate.json
            docker exec -i whois ./cc-test-reporter upload-coverage

        - name: Push Docker image to Docker hub
          env:
            USERNAME: ${{ secrets.DOCKER_USERNAME }}
            PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            docker login -u "$USERNAME" -p "$PASSWORD"
            docker push $(cat TAG)
