name: build, test and deploy on pr

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
          SHORT_SHA=$(git describe --always)
          echo "ghcr.io/internetee/whois:RC_$SHORT_SHA" > TAG

      - name: Build image
        run: |
          docker build -t $(cat TAG) -f Dockerfile.generic .

      - name: Test
        run: |
          docker network create --driver bridge test-net
          docker run -d -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGERS_DB=db -p 5433:5432 --name db --network=test-net postgres:9.6
          sleep 5
          docker run -d -e WHOIS_ENV=test -e RAILS_ENV=test -e APP_DBHOST=db -e GIT_COMMIT_SHA="$(cat GIT_COMMIT_SHA)" -e GIT_BRANCH=$(cat GIT_BRANCH) --name whois --network=test-net $(cat TAG) tail -f /dev/null
          docker exec -i whois rake db:create
          docker exec -i whois rake db:schema:load
          docker exec -i whois rake test

      - name: Push Docker image to gh container registry
        env:
          PASSWORD: ${{ secrets.GHCR }}
        run: |
          echo $PASSWORD | docker login ghcr.io -u eisbot --password-stdin
          docker push $(cat TAG)

  temporarily_disable_deploy:
    runs-on: ubuntu-20.04
    needs: build_and_test
    steps:
      - name: Set variable
        run: echo "is_self-hosted_runner_safe=false" >> $GITHUB_ENV

  deploy:
    if: github.IS_SELF-HOSTED_RUNNER_SAFE == true
    needs: 
    - build_and_test
    - temporarily_disable_deploy
    runs-on: [self-hosted, helm-kubectl]
    env:
      K_CONFIG: ${{ secrets.KUBE_CONFIG }}
    steps:
      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
          SHORT_SHA=$(git describe --always)
          echo "RC_$SHORT_SHA" > TAG

      - name: Upgrade whois in whois-testing
        run: |
          echo $K_CONFIG | base64 -di > kubeconfig
          export KUBECONFIG=./kubeconfig
          helm upgrade --install whois --set "image.tag=$(cat TAG)" charts --namespace=whois-testing
