name: build, test and deploy test environment on pr

on:
  push:
    branches:
    - add-build-test-pipeline
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04
    continue-on-error: true
  
    steps:

        - uses: actions/checkout@v2

        - name: Set image tag
          run: |
            SHORT_SHA=$(git describe --always)
            echo "internetee/whois:RC_$SHORT_SHA" > TAG

        - name: Set ENV for codeclimate (push)
          run: |
            echo "GIT_BRANCH=$GITHUB_REF" >> GITHUB_ENV
            echo "GIT_COMMIT_SHA=$GITHUB_SHA" >> GITHUB_ENV
          if: github.event_name == 'push'

        - name: Build image
          run: |
            docker build -t $(cat TAG) .
        
        - name: Test
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          run: |
            docker network create --driver bridge test-net
            docker run -d --name db --network=test-net internetee/whois_tester_postgres:1
            docker run -d -e WHOIS_ENV=test -e APP_DBHOST=db -e GITHUB_ENV="$(cat GITHUB_ENV)" -e GIT_BRANCH=$GITHUB_REF -e CC_TEST_REPORTER_ID --name whois --network=test-net $(cat TAG) tail -f /dev/null
            docker exec -i whois rake test

        - name: Get and upload test results
          run: |
            docker exec -i whois ./cc-test-reporter format-coverage --output coverage/codeclimate.json
            docker exec -i whois ./cc-test-reporter sum-coverage coverage/codeclimate.json
            docker exec -i whois ./cc-test-reporter upload-coverage
