name: Test and Coverage

on:
  push:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    services:
      postgres:
        image: postgres:18
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USERNAME: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ruby: ['3.4.5']
    runs-on: ${{ matrix.os }}
    env:
      PG_DATABASE: postgres
      PG_HOST: localhost
      PG_USER: postgres
      PG_PASSWORD: password
      PG_PORT: 5432
      RAILS_ENV: test
      COVERAGE: true
      DISABLE_SPRING: 1

    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Prepare database config
        run: cp config/database-example.yml config/database.yml

      - name: Set up database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Run tests with coverage
        run: bundle exec rake test test/*

      - uses: qltysh/qlty-action/coverage@v2
        if: github.event_name == 'push'
        with:
          oidc: true
          files: coverage/.resultset.json

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/.resultset.json
            coverage/index.html
            coverage/assets/
          include-hidden-files: true
