name: Test the code 

on:
  - push

jobs:

  build_and_test:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)
          echo "TAG=ghcr.io/internetee/whois:RC_$SHORT_SHA" >> $GITHUB_ENV

      - name: Get branch name
        run: |
          OIFS=$IFS
          IFS='/'
          read -a parts <<< "$GITHUB_REF"
          IFS=OIFS
          echo "BRANCH=${parts[2]}" >> $GITHUB_ENV
          echo $BRANCH
      
      - name: Build image
        run: |
          echo $TAG
          docker build -t $TAG -f Dockerfile.generic .

      - name: Test
        run: |
          docker network create --driver bridge test-net
          docker run -d -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGERS_DB=db -p 5433:5432 --name db --network=test-net postgres:9.6
          sleep 5
          docker run -d -e WHOIS_ENV=test -e RAILS_ENV=test -e APP_DBHOST=db -e GIT_COMMIT_SHA="$GITHUB_SHA -e GIT_BRANCH=$GIT_BRANCH --name whois --network=test-net $TAG tail -f /dev/null
          docker exec -i whois rake db:create
          docker exec -i whois rake db:schema:load
          docker exec -i whois rake test